### ISSUE TITLE
NodeMCU-Hardware.h also must be downloaded

### ISSUE THREAD

**Issue by SBerneberg** [jmalins/BattleBot-Control#6]
At least on my setup, I had to also download the "NodeMCU-Hardware.h" file and place it in the same folder as the .ino file. This is not documented.

**Comment by SBerneberg** [comment]
Ah. Everything must be downloaded. Including the data folder. Nevermind.

**Comment by jmalins** [comment]
Thanks for the comment. I added a note about downloading the entire repository to the installation directions.
