### ISSUE TITLE
Link for cheap motors is broken

### ISSUE THREAD

**Issue by Jeff-Haas** [jmalins/BattleBot-Control#8]
Unfortunately, you already have to update the link for the motors.  It goes to a dead page on AliExpress.

**Comment by jmalins** [comment]
Thanks for the heads-up. I updated it, but I have a feeling we're going to have a hard time keeping it working.

**Comment by Jeff-Haas** [comment]
It's probably a good idea to put a picture and basic description of what people should search for, with a note that the link is likely to become invalid. 
----- Original Message -----
